name: Build Executable

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 .NET 环境
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 编译项目 (.NET Framework 4.7.2)
      run: dotnet build WinToolsLauncher.csproj -c Release -o ./build_output

    - name: 上传纯单文件 EXE
      uses: actions/upload-artifact@v4
      with:
        name: WinToolsLauncher
        path: ./build_output/WinToolsLauncher.exe # 仅打包单独的 exe 文件
